name: Automatic testing (linux, no tobii)

on:
    schedule:
        - cron: '0 0 * * *'

jobs:
  Testing:

    runs-on: linux-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v1

      - name: Checkout externals
        run: |
          git submodule init
          git submodule update

      - name: Install PsychoPy
        run: pip install psychopy

      - name: Install Pyglet
        run: pip install pyglet==1.3.2

      - name: Install Pytest
        run: pip install pytest

      - name: Run tests
        run: |
          cd test
          pytest