name: Automatic testing

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - name: Run tests
      working-directory: ./test
      run: |
        pip install pytest
        pytest
