name: Automatic testing

on: [push]

jobs:
  test:

    runs-on: windows-latest

    steps:
      - name: Checkout code        
        uses: actions/checkout@v1
      - name: Install dependencies
        run: |
          pip install psychopy
          pip install pyglet==1.3.2
          pip install pytest
          
      - name: Run tests
        run: |
          cd test
          pytest
