name: Automatic testing

on: [push]

jobs:
  test:

    runs-on: windows-latest

    steps:
      - name: checkout        
        uses: actions/checkout@v1
      - name: Run tests
        run: |
          pip install pytest
          cd test
          pytest
